version: '3.8'
services:
  dev-db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: bookmark_app
    networks:
      - my_network

networks:
  my_network: